In [ ]:
a = input(" Enter a value: ")
a = int(a)
count = 0
for i in range(1, a + 1, 1):
  if (a % i == 0):
    count+=1
if (count == 2):
   print("The given number is prime.")
else:
  print("The given number is not prime.")

 Enter a value: 10
The given number is not prime.

In [ ]:
a = input(" Enter a value: ")
a = int(a)
def fib(num):
  if (num == 0 or num == 1):
   return num
  else:
   return fib(num-1) + fib(num-2)

print(f"The fibonacci series for {a} is as follows")
for i in range(0 ,a+1 ,1):
  print(fib(i))

 Enter a value: 3
The fibonacci series for 3 is as follows
0
1
1
2

In [ ]:
print(" Enter two values a,b")
a = input()
b = input()
a = int(a)
b = int(b)
min = a if (a < b) else b
max = a if (a > b) else b
for i in range(1, min+1, 1):
   if( (a % i == 0 ) and (b % i == 0) ):
    GCD = i

for j in range(max, (a*b)+1, 1):
  if( (j % a == 0) and (j % b == 0)):
    LCM = j

print(f"The GCD of {a} and {b} is {GCD}")
print(f"The LCM of {a} and {b} is {LCM}")

 Enter two values a,b
4
5
The GCD of 4 and 5 is 1
The LCM of 4 and 5 is 20

In [ ]:
print(" Enter two values a,b")
a = input()
b = input()
a = int(a)
b = int(b)
print("Enter the operator")
c = input()
c = str(c)
def calculator(c):
    if c == '+':
        return a + b
    elif c == '-':
        return a - b
    elif c == '*':
        return a * b
    elif c == '/':
        return a / b
    elif c == '%':
        return a % b
    else:
        return "Invalid operator"

print(calculator(c))

 Enter two values a,b
1
9
Enter the operator
-
-8

In [ ]:
print(" Enter number of elements")
n = input()
n = int(n)
arr = [0] * n
for i in range(0, n, 1):
  arr[i] = input()

for i in range(0, n, 1):
  arr[i] = int(arr[i])

new_list = list(set(arr))
print(new_list)

 Enter number of elements
4
1
2
3
1
[1, 2, 3]

In [ ]:
dict = {"one" : 1, "two" : 2, "three" : 3, "four" : 4, "five" : 5}
print(dict)

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}

In [ ]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

In [ ]:
import pandas as pd
data = {
    'Name': ['Pallavi', 'Ananya', 'Priya', 'Vaishnavi'],
    'Roll_no': [23, 22, 12, 29],
    'Section': ['CSM-A', 'IT-B', 'CSD-C', 'CSM-C'],
    'Fees': ['No due','No due','due','No due']
}
df = pd.DataFrame(data)
print(df)
df.to_csv('output.csv', index=False)
print("CSV file created successfully!")

        Name  Roll_no Section    Fees
0    Pallavi       23   CSM-A  No due
1     Ananya       22    IT-B  No due
2      Priya       12   CSD-C     due
3  Vaishnavi       29   CSM-C  No due
CSV file created successfully!

In [ ]:
import random
import string
char = string.ascii_letters + string.digits + string.punctuation
print("Enter number of characters in password")
n = input()
n = int(n)
password = ''.join(random.choice(char) for _ in range(n))
print(password)

Enter number of characters in password
3
],N